"""initial migration

Revision ID: 14889e822343
Revises: None
Create Date: 2016-09-19 02:53:52.085000

"""

# revision identifiers, used by Alembic.
revision = '14889e822343'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
