"""initial migration

Revision ID: 753e82be1126
Revises: None
Create Date: 2016-09-19 09:19:06.043000

"""

# revision identifiers, used by Alembic.
revision = '753e82be1126'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###
