"""initial migration

Revision ID: ad02f04e45a7
Revises: None
Create Date: 2016-09-19 18:41:23.204000

"""

# revision identifiers, used by Alembic.
revision = 'ad02f04e45a7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###
