"""initial migration

Revision ID: beaadfbbd8c3
Revises: 753e82be1126
Create Date: 2016-09-19 09:47:53.363000

"""

# revision identifiers, used by Alembic.
revision = 'beaadfbbd8c3'
down_revision = '753e82be1126'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
