"""initial migration

Revision ID: d3aae9bdc63f
Revises: ad02f04e45a7
Create Date: 2016-09-19 18:44:48.117000

"""

# revision identifiers, used by Alembic.
revision = 'd3aae9bdc63f'
down_revision = 'ad02f04e45a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
